name: "high_resolution"
description: "Configuration pour l'entraînement haute résolution"

inherit: "default"  # Hérite de la configuration par défaut

model:
  patch:
    size: 512
    overlap: 64

preprocessing:
  target_size: [2048, 2048]

training:
  batch_size: 4  # Réduit à cause de la mémoire
  learning_rate: 5e-5 