# Configuration de base
name: "default"
description: "Configuration par défaut"

# Chemins des données (seront ajustés automatiquement selon l'environnement)
paths:
  dataset_dir: "${environment.data_root}/dataset"  # sera résolu automatiquement
  bw_dir: "${paths.dataset_dir}/source/bw"
  color_dir: "${paths.dataset_dir}/source/color"
  metadata_dir: "${paths.dataset_dir}/metadata"
  attention_maps_dir: "${paths.dataset_dir}/attention_maps"
  patches_dir: "${paths.dataset_dir}/patches"
  models_dir: "${environment.data_root}/models"
  best_attention_model_path: "${paths.models_dir}/best_attention_model.pth"

# Configuration du modèle
model:
  vit:
    model_name: "vit_b_16"
    pretrained: true
    feature_size: 768
  deeplab:  # Ajout de la configuration DeepLabV3
    pretrained: true
    backbone: "resnet50"
  attention:
    min_points: 5
    min_score_threshold: 0.3
    max_points: 15
    head_hidden: 512
    gaussian_sigma: 42.67  # 128/3
    loss_weights:
      diversity: 1.0
      coverage: 0.5
      grid: 1.0
      score_concentration: 0.3
      complexity: 0.5
  patch:
    size: 256
    overlap: 32

# Configuration de l'entraînement
training:
  batch_size: 8
  learning_rate: 1e-4
  num_epochs: 50
  device: "cuda"  # sera automatiquement géré par le code
  optimizer:
    type: "adam"
    beta1: 0.9
    beta2: 0.999
  scheduler:
    type: "cosine"
    warmup_epochs: 5

# Configuration des métriques
metrics:
  structural_weight: 0.7
  transition_weight: 0.3
  quality_threshold: 50

# Configuration du preprocessing
preprocessing:
  target_size: [1024, 1024]
  normalize: true
  augmentation: true

# Configuration des données de validation
data:
  training_dataset:
    gdrive_url: "https://drive.google.com/file/d/1RWt9kawzXyIvvZWDmEv9e4QrXpqbgac0/view?usp=share_link"
    target_images: 5000  # Nombre d'images souhaité pour l'entraînement
  inference_dataset:
    gdrive_url: "https://drive.google.com/file/d/1F9YwjozTfhTLugxX-GKQc7hnkhy7JusG/view?usp=share_link"
    target_images: 100  # Nombre d'images souhaité pour l'inférence
  validation_split: 0.2  # 20% des données pour la validation